name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone themes
        run: |
          git clone --depth 1 https://github.com/Mogeko/mogege themes/mogege
          git clone --depth 1 https://github.com/liuzc/LeaveIt themes/LeaveIt

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.94.2'
          extended: true

      - name: Build
        run: hugo --gc --minify

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd public
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/Duder-git/Duder-git.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy from GitHub Actions"
          git push -f origin gh-pages